// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zEUNF56liLIEBya2EcKOnEzy-cswRdU',
    appId: '1:967848372324:web:2fe4ba3162f045f7e6d771',
    messagingSenderId: '967848372324',
    projectId: 'e-commerce-54075',
    authDomain: 'e-commerce-54075.firebaseapp.com',
    storageBucket: 'e-commerce-54075.appspot.com',
    measurementId: 'G-VB49NWCB27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVUZYbIcyPwRJSd6DDq0l2WFt5ZNa4vk',
    appId: '1:967848372324:android:ea7cdef8a886f49be6d771',
    messagingSenderId: '967848372324',
    projectId: 'e-commerce-54075',
    storageBucket: 'e-commerce-54075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAxKzSAW1mwrvard-9ge1IqUGHapwG_E4',
    appId: '1:967848372324:ios:bab6929a8a9f6f7ce6d771',
    messagingSenderId: '967848372324',
    projectId: 'e-commerce-54075',
    storageBucket: 'e-commerce-54075.appspot.com',
    androidClientId: '967848372324-9alp50v0472r936h8jolf5hec9pc4mes.apps.googleusercontent.com',
    iosClientId: '967848372324-e8c6soip4hodhr0t62bu24cg66vc8hvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAxKzSAW1mwrvard-9ge1IqUGHapwG_E4',
    appId: '1:967848372324:ios:fc3856c95b4451f3e6d771',
    messagingSenderId: '967848372324',
    projectId: 'e-commerce-54075',
    storageBucket: 'e-commerce-54075.appspot.com',
    androidClientId: '967848372324-9alp50v0472r936h8jolf5hec9pc4mes.apps.googleusercontent.com',
    iosClientId: '967848372324-5ocj4bpkpuo69jd2os7js9our1am5iqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
